version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule: { interval: weekly }
    groups:
      spring:
        patterns: ["org.springframework*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
  - package-ecosystem: docker
    directory: /docker
    schedule: { interval: monthly }
